services:
    mongohost:              
        image: mongo:7     
        restart: always    
        container_name: resourcebookingmongodb
        volumes:
         - dbdata:/data/db
        ports:
        - 27017:27017
      
    web:
        build: .        
        restart: always
        container_name: resourcebookingwebapi
        ports:
          - 5000:8080 
        depends_on:     
          - mongohost
        environment:
          MONGO_CON_STR: ${MONGO_CON_STR}
          MONGO_DB_NAME: ${MONGO_DB_NAME}
          GH_CDN_PAT: ${GH_CDN_PAT}
          GH_API_URL: ${GH_API_URL}
          JWT_KEY: ${JWT_KEY}
        env_file:
        - .env

volumes:                
  dbdata: 